### ISSUE TITLE
Is there any way to send package L2Clicli

### ISSUE THREAD

**Issue by w3nder** [nartallax/gaming#1] opened 2019-12-01 05:21 UTC

**Comment by nartallax** [comment] 2019-12-01 15:59
Oh wow, someone actually tried to use this :3

As you can expect from tool name, all the actions are done via stdin and stdout (in json). You write action to stdin of the tool, and receive actions from server from stdout of the tool. Most of the time, one action corresponds to one package.

This tool never aimed to support all known packages. You can see what packages it support in packages/to_game_server.c and packages/from_game_server.c.

That is, for accept party request, you should write to stdin
`{"type":"AnswerJoinParty","ok":true}\n`
and to leave, 
`{"type":"LeaveParty"}\n`
(where \n is newline)

This tool provides no automation capabilities. Originally, it was used through omnipresense2 (commited a lot of files there just now btw)

> some way to send 1 by 1 packet looking for a txt like the l2walker script  

No, there is no such option.

**Comment by WeenderT** [comment] 2019-12-01 20:13
Not just tried. how I want to continue until I get where I want :)
And this project helped me a lot. and I still play a c4 server (656) and it worked

My question
![pt](https://user-images.githubusercontent.com/1123103/69919605-68252400-145d-11ea-9100-41e721956a4c.PNG)
it was like answering when I get this package {"type":"PartyRequest","from":"Pitty."}

With your answer I will try.

My goal is to make the program work like this.

I login to an Aio buffer account and it accept pt and buffar and exit pt. And when I'm done I'll share it with you.

And the client wants vue.js and make a web bot

**Comment by WeenderT** [comment] 2019-12-01 20:31
`void encodeGameAnswerJoinParty(json_value* obj, Binwriter* writer){
	writeByte(writer, 0x2a);
	writeInt(writer, jsonValueByKey(obj, "ok")->u.boolean? 1: 0);
}

void encodeGameLeaveParty(json_value* obj, Binwriter* writer){
	writeByte(writer, 0x2b);
}`

That way it already existed, wasn't it to accept PT?

**Comment by nartallax** [comment] 2019-12-01 20:39
I'm not sure what are you trying to ask.

When you write action in JSON into stdin, it gets parsed and one of these functions is invoked. So, when you write `{"type":"AnswerJoinParty","ok":true}` - tool sends package with id 0x2a and 1 as int - and this is package that responds to party request.

**Comment by WeenderT** [comment] 2019-12-01 20:40
So I have to use another tool to answer the package?

**Comment by nartallax** [comment] 2019-12-01 20:47
No.

You see, this tool is client in some way. It differs from original client - it does not provides graphical interface, but provides command-line interface. When you, as player, use original client - you clicks the graphical interface; when you use this client - you write json into stdin.

I think it's will be impossible to receive packages with this client and answer with another - because this client "owns" TCP-connection to server; because client knows some cryptographical values that are required to correctly encypher packages; and so on.

To accept the party, you need to send package with id 0x2a; to make the client send this package, you need to write `{"type":"AnswerJoinParty","ok":true}` into its stdin.

(maybe I don't get something that you ask?)

**Comment by WeenderT** [comment] 2019-12-01 20:58
Thanks for the reply sorry my various question.

I will look for how to answer the package why when I go through the terminal. and send pt with another account logged in l2.exe I get the package

`./l2clicli --auth-host 127.0.0.1 --auth-port 2106 --login xxx--password xx--nick xxx --token 5F3B352E5D39342D33313D3D2D257854215E5B24 --protocol 656 --server-id 1`

Now I will try to write the answer to stdin

**Comment by WeenderT** [comment] 2019-12-01 21:42
nice :) 
`cat ./cmd.txt | ./l2clicli...`
cmd.txt value `{"type":"AnswerJoinParty","ok":true}`

I was able to send the package, the account accepted the part but a few seconds later
Failed to write into TCP socket: error code -1

**Comment by nartallax** [comment] 2019-12-01 21:51
That's strange.

Actually, I haven't touched this tool for a while and for now can't remember exactly what can go wrong.

You can just grab the code and continue development on your own. There is not much I can help you with.

**Comment by nartallax** [comment] 2019-12-01 21:55
Maybe the reason is `cat` will close its output stream when done, and I've wrote the client keeping in mind that stdin won't be closed. But it probably should not be the cause of TCP errors? Don't know for sure. Debug probably can reveal that, but I don't have time for that now.

**Comment by WeenderT** [comment] 2019-12-01 22:11
have you helped me so much ..
I will continue and when it has evolved I'll be back here to show you

Thank you again.

**Closed as not planned by WeenderT** 2019-12-01 22:11 UTC
